# Generated by Django 5.0.2 on 2025-03-04 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('fruits', 'Fruits & Vegetables'), ('dairy', 'Dairy & Breakfast'), ('snacks', 'Snacks & Munchies'), ('beverages', 'Cold Drinks & Juices'), ('staples', 'Atta, Rice & Dal'), ('spices', 'Masala & Spices'), ('cleaning', 'Cleaning Essentials'), ('personal_care', 'Personal Care'), ('baby_care', 'Baby Care'), ('home_kitchen', 'Home & Kitchen'), ('paan_corner', 'Paan Corner'), ('pharma_wellness', 'Pharma & Wellness'), ('electronics', 'Electronics & Accessories'), ('beauty', 'Beauty & Makeup'), ('pet_supplies', 'Pet Care'), ('meat_fish', 'Meat & Fish'), ('instant_food', 'Ready to Cook & Eat'), ('bakery', 'Bakery & Biscuits'), ('household', 'Household Items')], max_length=50)),
                ('image_url', models.URLField()),
                ('rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
